mongodb:
  address: "mongodb://localhost:27017"
  databaseName: "bucket"
kafka:
  bootstrapAddress: "localhost:9092"
  consumer:
    groupId: "test-group"
  topics:
    - name: "topics"
      partitionsNumber: 5
      replicationFactor: 1
    - name: "buckets"
      partitionsNumber: 5
      replicationFactor: 1
